# Generated by Django 2.1.7 on 2019-03-28 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citekey', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Error: only alphanumeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')])),
                ('species', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')])),
                ('isi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Must be a number between 0.0 and 1.0'), django.core.validators.MaxValueValidator(1.0, message='Must be a number between 0.0 and 1.0')], verbose_name='Index of Self-Incompatibility')),
                ('fruit_type', models.CharField(blank=True, choices=[('capsule', 'capsule'), ('CAPSULE', 'CAPSULE'), ('Capsule', 'Capsule'), ('berry', 'berry'), ('Berry', 'Berry'), ('BERRY', 'BERRY')], default='none', max_length=50, null=True)),
                ('pub_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Traitable.Pub')),
            ],
        ),
    ]
