# Generated by Django 2.1.7 on 2019-03-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0002_auto_20190328_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='pub_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Traitable.Pub', verbose_name='citekey'),
        ),
    ]
