# Generated by Django 2.1.7 on 2019-03-28 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0004_auto_20190328_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='pub',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='pub',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='pub',
            name='pub_type',
            field=models.CharField(blank=True, choices=[('article', 'article'), ('book', 'book')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='genus',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='trait',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')]),
        ),
    ]
