# Generated by Django 2.1.7 on 2019-03-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0005_auto_20190328_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='pub_type',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='title',
        ),
    ]
