# Generated by Django 2.1.7 on 2019-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0008_auto_20190328_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pub',
            options={'verbose_name_plural': 'Pubs'},
        ),
        migrations.AddField(
            model_name='pub',
            name='pub_type',
            field=models.CharField(blank=True, choices=[('article', 'article'), ('book', 'book')], max_length=50, null=True),
        ),
    ]
