# Generated by Django 2.1.7 on 2019-03-28 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0009_auto_20190328_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')], verbose_name="Author's Last name"),
        ),
        migrations.AlterField(
            model_name='pub',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publication name'),
        ),
    ]
