# Generated by Django 2.1.7 on 2019-04-01 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traitable', '0010_auto_20190328_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')], verbose_name="Author's first name"),
        ),
        migrations.AlterField(
            model_name='pub',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')], verbose_name="Author's last name"),
        ),
        migrations.AlterField(
            model_name='pub',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Error: only alphabetic characters are allowed.')], verbose_name="Author's middle name"),
        ),
    ]
